
export interface IWork {
    _id?: string,
    id?: string,
    userId: string,
    workerId: string,
    serviceId: string,
    categoryId: string,
    category: string,
    service: string,
    workerName: string,
    userName: string,
    wagePerHour: string,
    platformFee: string,
    commission: string,
    totalHours: string,
    totalAmount: string,
    location: {
        address: string,
        pincode: string,
        lat: number,
        lng: number
    },
    size: string,
    description: string,
    sheduleDate: string,
    sheduleTime: string,
    status?: string,
    paymentStatus?: string,
    createdAt?: Date,
    updatedAt?: Date,
}