export const API_ROUTES = {

  USER: {
    REGISTER: "/register",
    LOGIN: "/login",
    HOME: "/home",
    LANDING: "/",
    PROFILE: "/profile",
    VERIFY_OTP: "/verify-otp",
    FORGOT_PASS: "/forgot-password",
    RESET_PASS: "/reset-password",
    WORK_DETAILS: "/work-details",
    NOTIFICATIONS: "/notifications",
    MESSAGE: "/message",
  },

  ADMIN: {
    LOGIN: "/admins/login",
    REGISTER: "/admins/register",
    DASHBOARD: "/admins/dashboard",
    FORGOT_PASS: "/admins/forgot-password",
    LOGOUT: "/admins/logout"
  },

  WORKER: {
    REGISTER: "/workers/register",
    DASHBOARD: "/workers/dashboard",
    LOGIN: "/workers/login",
    LANDING: "/workers",
    VERIFY_OTP: "/workers/verify-otp",
    FORGOT_PASS: "/workers/forgot-password",
    RESET_PASS: "/workers/reset-password",
    NOTIFICATION: "/workers/notifications",
  },

  ADMIN_SERVICE: {
    LOGIN: "admins/login",
    LOGOUT: "admins/logout",
    FETCH_USERS: "admins/users",
    SET_USER_STATUS: "admins/users/set-status",
    FETCH_WORKERS: "admins/workers",
    SET_WORKER_STATUS: "admins/workers/set-status",
    FETCH_NON_VERIFIED_WORKERS: "admins/workers-nonVerify",
    APPROVE_WORKER: "admins/approve-worker",
    REJECT_WORKER: "admins/reject-worker",
    FETCH_AVAILABILITY: "admins/fetch-availability",
    FETCH_CATEGORY: "categories/categories",
    CREATE_CATEGORY: "categories/create-category",
    UPDATE_CATEGORY: "categories/update",
    DELETE_CATEGORY: "categories/delete",
    TOGGLE_CATEGORY_ACTIVE: "categories/set-active",
    FETCH_SERVICES: "services/getAll-services",
    CREATE_SERVICE: "services/create-service",
    UPDATE_SERVICE: "services/update",
    DELETE_SERVICE: "services/delete",
    TOGGLE_SERVICE_ACTIVE: "services/set-active",
    FETCH_WORKS: "works/works",
    FETCH_TOP_THREE_WORKS: "works/get-top-three",
    FETCH_EARNINGS: "admins/earnings",
    FETCH_WALLET: "admins/wallet",
    CREATE_SUBSCRIPTION: "subscription/create-subscription-plan",
    FETCH_SUBSCRIPTIONS: "subscription/fetch-all",
    DELETE_SUBSCRIPTION: "subscription/delete",
    TOGGLE_SUBSCRIPTION_STATUS: "subscription/toggle-status",
    UPDATE_SUBSCRIPTION: "subscription/update",
  },

  USER_SERVICE: {
    REGISTER: "users/register",
    LOGIN: "users/login",
    LOGOUT: "users/logout",
    FETCH_USER: "users/fetch-data",
    UPDATE_USER: "users/update",
    FORGOT_PASSWORD: "users/forgot-password",
    RESEND_OTP: "users/resend-otp",
    VERIFY_OTP: "users/verify-otp",
    RESET_PASSWORD: "users/reset-password",
    FETCH_SERVICES: "services/getAll-services",
    FETCH_SERVICE_BY_SEARCH: "services/by-search",
    FETCH_SERVICE_BY_ID: "services/By-Id",
    FETCH_CATEGORY_BY_ID: "categories/By-Id",
    FETCH_AVAILABILITY: "users/fetch-availability",
    CREATE_WORK: "works/creat-work",
    FETCH_WORK_HISTORY: "works/users",
    CANCEL_WORK: "works/cancel",
    FIND_USERS_BY_IDS: "users/find-users-byId",
    FETCH_CHAT: "chats/fetch-chat",
    RATE_WORKER: "workers/ratings",
  },

  WORKER_SERVICE: {
    REGISTER: "workers/register",
    LOGIN: "workers/login",
    LOGOUT: "workers/logout",
    BUILD_ACCOUNT: "workers/build-account",
    FETCH_DETAILS: "workers/fetch-details",
    UPDATE: "workers/update",
    WALLET: "workers/wallet",
    EARNINGS: "workers/earnings",
    FIND_BY_IDS: "workers/find-workers-byId",
    FORGOT_PASSWORD: "workers/forgot-password",
    RESEND_OTP: "workers/resend-otp",
    VERIFY_OTP: "workers/verify-otp",
    RESET_PASSWORD: "workers/reset-password",
    SEARCH: "workers/search",
    FETCH_WORK_HISTORY: "works/workers",
    FETCH_WORK_DETAILS: "works/details",
    ACCEPT_WORK: "works/accept",
    COMPLETE_WORK: "works/is-completed",
    ASSIGNED_WORKS: "works/assigned-works",
    REQUESTED_WORKS: "works/requested-works",
    FETCH_CATEGORIES: "categories/categories",
    SERVICE_BY_CATEGORY: "services/by-categories",
    FETCH_WORKER_CATEGORY: "categories/by-worker",
    FETCH_WORKER_SERVICE: "services/by-worker",
    FETCH_SUBSCRIPTIONS: "subscription/fetch-all",
    ACTIVATE_SUBSCRIPTION: "subscription/activate-plan",
  },

};
